Update to signature verification after name change manifest
decred/decred-release pull request #169
Opened 2020-02-13 21:13 UTC by SovereignNode

Hi,

First pull request ever, so I'm not sure how this all works. :)

I was trying to install dcrd and came across different manifest naming convention since a few releases. I updated the README file with how I did it.

The gpg --verify command says 'Good Signature' but I can't actually find the same value in the previous step like the original example had. Did I run the commands correctly?

Cheers

2020-02-21 19:15 UTC, jrick requested changes

2020-02-21 19:15 UTC, jrick commented on README.md
> +   a53004599daeab51c0e86af026748b7aa55ff9e5d4844bef3b7d8ccf8a5d72a9  dcrinstall-linux-amd64-v1.5.1
use the real sha256 for this file here to avoid confusion

2020-02-21 19:15 UTC, jrick commented on README.md
> +   $ gpg --keyserver pgp.mit.edu --recv-keys 0x518A031D
keys should be received using the long fingerprint

2020-10-28 20:01 UTC, marcopeereboom commented
Timeout. Resubmit with requested fixes if you feel strong about this.

2020-10-28 20:01 UTC, closed without merging